export const LANG = {
  id: {
    dashboard:"Beranda", transactions:"Transaksi", report:"Laporan", date:"Date", settings:"Pengaturan",
    monthlyExpense:"Pengeluaran bulan ini", today:"Hari ini", remaining:"Sisa", budgetLeft:"tersisa",
    morning:"Selamat pagi", afternoon:"Selamat siang", evening:"Selamat sore", night:"Selamat malam",
    savingsGoal:"Target Tabungan", recentTx:"Transaksi Terbaru", seeAll:"Lihat Semua",
    breakdown:"Breakdown Kategori", weeklyTrend:"Tren Mingguan", monthlyBudget:"Budget Bulanan",
    addTx:"Tambah Transaksi", editTx:"Edit Transaksi", newTx:"Transaksi Baru", save:"Simpan", cancel:"Batal", delete:"Hapus",
    amount:"Jumlah", description:"Keterangan", category:"Kategori", location:"Lokasi", note:"Catatan",
    date_label:"Tanggal", addGoal:"Tambah Target", editGoal:"Edit Target",
    amountPlaceholder:"Jumlah (Rp)", descPlaceholder:"Keterangan...", locPlaceholder:"Lokasi (opsional)", notePlaceholder:"Catatan (opsional)",
    settingsTitle:"Pengaturan", profile:"Profil", profileName:"Nama profil",
    appearance:"TAMPILAN", displayMode:"Mode Tampilan", darkActive:"Mode gelap aktif", lightActive:"Mode terang aktif",
    followSystem:"Ikuti Sistem", followSystemDesc:"Otomatis dari pengaturan HP", manualMode:"Mode diatur manual",
    colorTheme:"Tema Warna", colorCustom:"Warna Custom", language:"Bahasa", languageDesc:"Pilih bahasa tampilan",
    notifications:"NOTIFIKASI", notifActive:"Aktif — setiap hari jam 9 malam", notifOff:"Nonaktif",
    data:"DATA", exportData:"Ekspor Data", exportCSV:"Ekspor CSV",
    exportReport:"Ekspor Laporan", dangerZone:"ZONA BAHAYA", resetData:"Reset Semua Data",
    resetConfirm:"Yakin ingin menghapus semua data? Tidak bisa dibatalkan.",
    income:"Pemasukan", editIncome:"Edit Pemasukan", monthlyIncome:"Pemasukan Bulanan (Rp)", incomePlaceholder:"Contoh: 5000000",
    txAdded:"Transaksi ditambahkan", txUpdated:"Transaksi diperbarui", txDeleted:"Transaksi dihapus", txUndo:"Batal",
    nameSaved:"Nama disimpan", incomeSaved:"Pemasukan diperbarui",
    safe:"Aman", warning:"Perhatian", critical:"Kritis",
    budgetSafe:"Budget aman", budgetWarn:"Perhatikan budget", budgetCrit:"Hampir habis",
    addTarget:"Tambah Target", editTarget:"Edit Target", goalName:"Nama Target", goalTarget:"Target (Rp)", goalSaved:"Sudah Ditabung (Rp)",
    goalColor:"Warna", saveTarget:"Simpan Target", goalReached:"Target tercapai!",
    goalOverdue:"Sudah lewat", goalDaysLeft:"hari lagi",
    goalNamePlaceholder:"Contoh: Ganti HP", goalAmtPlaceholder:"Contoh: 5000000", goalSavedPlaceholder:"Contoh: 1500000",
    noTx:"Belum ada transaksi", noGoal:"Belum ada target tabungan", addFirst:"Yuk, buat target pertamamu!",
    noTxDesc:"Mulai catat pengeluaran hari ini", noTxDescEmpty:"Yuk, mulai catat pengeluaran pertamamu hari ini!",
    noTxFound:"Tidak ditemukan", noTxFoundDesc:"Tidak ada hasil untuk",
    startDesc:"Mulai catat pengeluaran untuk melihat laporan dan insight keuanganmu.",
    thisWeek:"Minggu Ini", avgPerDay:"Rata-rata/hari", transactions_label:"transaksi",
    add:"Tambah", edit:"Edit", from:"dari", days:"hari berjalan", done:"Selesai", use:"Gunakan", active:"Aktif",
    tapName:"Tap untuk isi nama", namePlaceholder:"Nama kamu...", search:"Cari transaksi...",
    filterToday:"Hari ini", filterWeek:"Minggu ini", filterMonth:"Bulan ini",
    thisMonth:"Bulan ini", lastMonth:"Bulan lalu",
    budgetLimit:"Budget Limit", budgetLimitDesc:"Atur batas pengeluaran per kategori",
    manageCategory:"Kelola Kategori", addCategory:"Tambah Kategori", editCategory:"Edit Kategori",
    catName:"Nama kategori...", pickIcon:"Pilih Ikon:", pickColor:"Pilih Warna:",
    previewLabel:"Preview", activeCategories:"Kategori Aktif",
    pickDate:"Pilih Tanggal", avgPerTx:"Rata-rata per transaksi:", noTxDate:"Tidak ada transaksi pada tanggal ini",
    setLimit:"Batas",
    addWishlist:"Tambah Wishlist Date", wishlistPlaceholder:"Contoh: Dinner di rooftop...",
    recordDate:"Catat Pengeluaran Date", noDateTx:"Belum ada pengeluaran date",
    noRecurring:"Belum ada transaksi rutin", recurAmtPlaceholder:"Jumlah (Rp)",
    recurNamePlaceholder:"Nama (mis: Kos, Netflix...)",
    themePreset:"PRESET TEMA", themeGreen:"Hijau", themeBlue:"Biru", themePurple:"Ungu", themeRose:"Merah", themeOrange:"Oranye", themeTeal:"Teal",
    orCustom:"atau custom", primaryLabel:"UTAMA", accentLabel:"AKSEN",
    primaryFull:"WARNA UTAMA", accentFull:"WARNA AKSEN",
    dailyReminder:"Pengingat Harian",
    dateBudgetTitle:"BUDGET DATE BULAN INI", dateActivities:"aktivitas date",
    wishlistTitle:"Wishlist Date", noWishlist:"Belum ada wishlist date",
    wishlistSub:"Tambahkan tempat impian kalian",
    dateRecord:"Catat Pengeluaran Date", noDateExp:"Belum ada pengeluaran date",
    addDateBtn:"+ Catat",
    targetDate:"Target Tanggal (opsional)",
    noData:"Belum ada data bulan ini", startNote:"Mulai catat pengeluaran hari ini",
    toastGoalSaved:"ok:Target tabungan disimpan", toastRecurAdd:"ok:Transaksi rutin ditambahkan",
    toastRecurEdit:"ok:Rutin diperbarui", toastRecurDel:"del:Rutin dihapus",
    toastWishlist:"ok:Ditambahkan ke wishlist", toastReportOk:"ok:Laporan berhasil dibuat",
    toastAddHome:"info:Tambahkan ke Home Screen dulu",
    toastReminderOn:"ok:Pengingat harian aktif jam 9 malam", toastReminderOff:"info:Pengingat dinonaktifkan",
    shareSummary:"Bagikan Ringkasan", shareCopied:"ok:Ringkasan disalin!", shareWhatsapp:"Bagikan ke WhatsApp", shareCopy:"Salin Teks",
    shareTitle:"Laporan Keuangan", swipeHint:"← Geser untuk hapus",
    addExpense:"+ Tambah Pengeluaran", addRecurring:"Tambah Rutin", recurringTx:"TRANSAKSI RUTIN",
    recurDay:"Tgl", recurEach:"tiap bulan", recurDeleted:"Rutin dihapus", recurEdited:"Rutin diperbarui", dayLabel:"Tgl (1-31):",
    autoApply:"Terapkan Otomatis", autoApplyDesc:"Catat otomatis tiap bulan saat tanggal tiba",
    allCategories:"Semua Kategori", breakdownCat:"Breakdown Kategori", trend8w:"Tren 8 Minggu",
    sortNewest:"Terbaru", sortOldest:"Terlama", sortHighest:"Terbesar", sortLowest:"Terkecil",
    totalExpense:"TOTAL PENGELUARAN", totalToday:"TOTAL HARI INI", perCategory:"Per Kategori",
    txDetail:"Detail Transaksi", insightToday:"Insight Hari Ini", topSpend:"Terbanyak:",
    aboveAvg:"Melebihi rata-rata harian", belowAvg:"Di bawah rata-rata harian",
    budgetMonthly:"BUDGET BULANAN", notEnoughData:"Belum cukup data",
    notEnoughDataDesc:"Grafik perbandingan antar bulan akan muncul setelah ada data dari 2 bulan berbeda.",
    goalRemaining:"Sisa", goalRemainingMore:"lagi",
    insightMore:"lebih banyak", insightLess:"lebih hemat", insightFrom:"dari bulan lalu",
    insightUp:"naik", insightDown:"turun",
    previewHeader:"Preview Header",
    deleteTxTitle:"Hapus Transaksi?", deleteTxDesc:"Transaksi ini akan dihapus permanen.",
    repInsightMonthly:"Insight Bulanan", repInsightWeekly:"Insight Mingguan",
    repWeekTotal:"Total minggu ini:", repMoreSpend:"Lebih boros", repLessSpend:"Lebih hemat",
    repVsLastWeek:"vs minggu lalu", repTopCat:"Kategori terbanyak:",
    showMore:"Lihat Lebih", backupData:"Backup Data", backupDesc:"Unduh semua data sebagai JSON", restoreBackup:"Pulihkan Backup", restoreDesc:"Import dari file backup", resetDesc:"Hapus semua data permanen", dataSubtitle:"Backup, pulihkan & reset", restoreConfirmMsg:"Restore backup ini? Data saat ini akan diganti.",
    backupOk:"Backup berhasil diunduh", restoreOk:"Backup berhasil dipulihkan!",
    restoreConfirm:"Restore backup ini? Data saat ini akan diganti.",
    backupInvalid:"File backup tidak valid",
    // Foto Struk
    receiptPhoto:"Foto Struk", addReceipt:"Tambah Foto Struk", viewReceipt:"Lihat Struk",
    receiptAdded:"ok:Foto struk disimpan", receiptDeleted:"del:Foto struk dihapus",
    receiptTap:"Tap untuk lihat/tambah struk", noReceipt:"Belum ada foto struk",
    receiptUpload:"Upload Foto Struk", receiptUploadDesc:"Tap untuk ambil foto atau dari galeri",
    receiptSave:"Simpan Struk",
    // Cicilan
    cicilan:"Cicilan", addCicilan:"Tambah Cicilan", editCicilan:"Edit Cicilan",
    cicilanName:"Nama Cicilan", cicilanTotal:"Total Pinjaman (Rp)", cicilanMonthly:"Cicilan/Bulan (Rp)",
    cicilanDue:"Jatuh Tempo (Tgl)", cicilanDuration:"Durasi (Bulan)", cicilanStart:"Mulai (Bulan/Tahun)",
    cicilanProgress:"Progress Cicilan", cicilanPaid:"Lunas", cicilanCurrent:"Bulan Ini", cicilanUpcoming:"Upcoming",
    cicilanMarkPaid:"Tandai Sudah Bayar", cicilanTotal2:"Total Cicilan/Bulan",
    cicilanRemain:"bulan lagi", cicilanOf:"dari", noCicilan:"Belum ada cicilan",
    cicilanDesc:"Cicilan auto dikurangi dari income tiap bulan",
    cicilanSaved:"ok:Cicilan disimpan", cicilanDeleted:"del:Cicilan dihapus",
    cicilanPaidToast:"ok:Ditandai sudah bayar",
    cicilanAlreadyPaid:"Sudah dibayar bulan ini",
    // Reminder
    reminderTitle:"Pengingat Transaksi", reminderDesc:"Notif kalau belum input pengeluaran hari ini",
    reminderTime:"Waktu Reminder", reminderDays:"Hari Aktif",
    reminderSmart:"Smart Reminder", reminderSmartDesc:"Skip kalau sudah ada transaksi hari ini",
    reminderPreview:"Preview Notifikasi",
    reminderNotifTitle:"💸 Belum catat pengeluaran hari ini!",
    reminderNotifBody:"Jangan lupa input transaksi biar keuanganmu tetap terkontrol 🐱",
    reminderOn:"ok:Pengingat aktif!", reminderOff:"info:Pengingat dinonaktifkan",
    // Tags
    tags:"Tag", addTag:"Tambah Tag", editTag:"Edit Tag", noTags:"Belum ada tag",
    tagPlaceholder:"cth: liburan, kondangan...", tagSuggestions:"Saran Tag",
    tagFilter:"Filter by Tag", tagAll:"Semua", tagStats:"Ringkasan per Tag",
    tagTx:"transaksi", tagAdded:"ok:Tag ditambahkan", tagDeleted:"del:Tag dihapus",
    tagSaved:"ok:Tag disimpan",
  },

  en: {
    // Nav
    dashboard:"Home", transactions:"Transactions", report:"Reports", date:"Date", settings:"Settings",
    // Dashboard card
    monthlyExpense:"Monthly spending", today:"Today", remaining:"Left", budgetLeft:"remaining",
    // Header greetings
    morning:"Good morning", afternoon:"Good afternoon", evening:"Good evening", night:"Good evening",
    // Sections
    savingsGoal:"Savings Goals", recentTx:"Recent Transactions", seeAll:"See All",
    breakdown:"Category Breakdown", weeklyTrend:"Weekly Trend", monthlyBudget:"Monthly Budget",
    // Forms
    addTx:"Add Transaction", editTx:"Edit Transaction", newTx:"New Transaction", save:"Save", cancel:"Cancel", delete:"Delete",
    amount:"Amount", description:"Description", category:"Category", location:"Location", note:"Note",
    date_label:"Date", addGoal:"Add Goal", editGoal:"Edit Target",
    amountPlaceholder:"Amount (Rp)", descPlaceholder:"Description...", locPlaceholder:"Location (optional)", notePlaceholder:"Note (optional)",
    // Settings
    settingsTitle:"Settings", profile:"Profile", profileName:"Profile name",
    appearance:"APPEARANCE", displayMode:"Display Mode", darkActive:"Dark mode active", lightActive:"Light mode active",
    followSystem:"Follow System", followSystemDesc:"Automatic from device settings", manualMode:"Mode set manually",
    colorTheme:"Colour Theme", colorCustom:"Custom Colour", language:"Language", languageDesc:"Choose display language",
    notifications:"NOTIFICATIONS", notifActive:"Active — every day at 9 PM", notifOff:"Inactive",
    data:"DATA", exportData:"Export Data", exportCSV:"Export CSV",
    exportReport:"Export Report", dangerZone:"DANGER ZONE", resetData:"Reset All Data",
    resetConfirm:"Are you sure you want to delete all data? This cannot be undone.",
    // Income
    income:"Income", editIncome:"Edit Income", monthlyIncome:"Monthly Income (Rp)",
    incomePlaceholder:"e.g. 5000000",
    // Toast
    txAdded:"Transaction added", txUpdated:"Transaction updated", txDeleted:"Transaction deleted", txUndo:"Undo",
    nameSaved:"Name saved", incomeSaved:"Income updated",
    // Budget status
    safe:"Safe", warning:"Warning", critical:"Critical",
    budgetSafe:"Budget on track", budgetWarn:"Watch your budget", budgetCrit:"Nearly exhausted",
    // Goals
    addTarget:"Add Goal", editTarget:"Edit Goal", goalName:"Goal Name", goalTarget:"Target (Rp)", goalSaved:"Amount Saved (Rp)",
    goalColor:"Colour", saveTarget:"Save Goal", goalReached:"Goal reached!",
    goalOverdue:"Overdue", goalDaysLeft:"days left",
    goalNamePlaceholder:"e.g. New Phone", goalAmtPlaceholder:"e.g. 5000000", goalSavedPlaceholder:"e.g. 1500000",
    // Misc
    noTx:"No transactions yet", noGoal:"No savings goals yet", addFirst:"Create your first goal!",
    noTxDesc:"Start recording your spending today", noTxDescEmpty:"Start recording your first transaction today!",
    noTxFound:"Not found", noTxFoundDesc:"No results for",
    startDesc:"Start recording expenses to see your reports and financial insights.",
    thisWeek:"This Week", avgPerDay:"Avg/day", transactions_label:"transactions",
    add:"Add", edit:"Edit", from:"of", days:"days elapsed", done:"Done", use:"Use", active:"Active",
    tapName:"Tap to set name", namePlaceholder:"Your name...", search:"Search transactions...",
    filterToday:"Today", filterWeek:"This week", filterMonth:"This month",
    thisMonth:"This month", lastMonth:"Last month",
    // Category manager
    budgetLimit:"Budget Limit", budgetLimitDesc:"Set spending limits per category",
    manageCategory:"Manage Categories", addCategory:"Add Category", editCategory:"Edit Category",
    catName:"Category name...", pickIcon:"Choose Icon:", pickColor:"Choose Colour:",
    previewLabel:"Preview", activeCategories:"Active Categories",
    // Report
    pickDate:"Pick Date", avgPerTx:"Average per transaction:", noTxDate:"No transactions on this date",
    setLimit:"Limit",
    // Date tab
    addWishlist:"Add Date Wishlist", wishlistPlaceholder:"e.g. Rooftop dinner...",
    recordDate:"Record Date Expense", noDateTx:"No date expenses yet",
    // Recurring
    noRecurring:"No recurring transactions yet", recurAmtPlaceholder:"Amount (Rp)",
    recurNamePlaceholder:"Name (e.g. Rent, Netflix...)",
    // Preview
    themePreset:"COLOUR PRESETS", themeGreen:"Green", themeBlue:"Blue", themePurple:"Purple", themeRose:"Rose", themeOrange:"Orange", themeTeal:"Teal",
    orCustom:"or custom", primaryLabel:"PRIMARY", accentLabel:"ACCENT",
    primaryFull:"PRIMARY COLOUR", accentFull:"ACCENT COLOUR",
    dailyReminder:"Daily Reminder",
    dateBudgetTitle:"THIS MONTH'S DATE BUDGET", dateActivities:"date activities",
    wishlistTitle:"Date Wishlist", noWishlist:"No date wishlist yet",
    wishlistSub:"Add your dream date spots",
    dateRecord:"Record Date Expense", noDateExp:"No date expenses yet",
    addDateBtn:"+ Record",
    targetDate:"Target Date (optional)",
    noData:"No data for this month", startNote:"Start recording expenses today",
    toastGoalSaved:"ok:Savings goal saved", toastRecurAdd:"ok:Recurring transaction added",
    toastRecurEdit:"ok:Recurring updated", toastRecurDel:"del:Recurring deleted",
    toastWishlist:"ok:Added to wishlist", toastReportOk:"ok:Report created",
    toastAddHome:"info:Add to Home Screen first",
    // Foto Struk
    receiptPhoto:"Receipt Photo", addReceipt:"Add Receipt Photo", viewReceipt:"View Receipt",
    receiptAdded:"ok:Receipt photo saved", receiptDeleted:"del:Receipt photo deleted",
    receiptTap:"Tap to view/add receipt", noReceipt:"No receipt photo yet",
    receiptUpload:"Upload Receipt Photo", receiptUploadDesc:"Tap to take photo or choose from gallery",
    receiptSave:"Save Receipt",
    // Cicilan
    cicilan:"Instalments", addCicilan:"Add Instalment", editCicilan:"Edit Instalment",
    cicilanName:"Instalment Name", cicilanTotal:"Total Loan (Rp)", cicilanMonthly:"Monthly Payment (Rp)",
    cicilanDue:"Due Date (Day)", cicilanDuration:"Duration (Months)", cicilanStart:"Start (Month/Year)",
    cicilanProgress:"Instalment Progress", cicilanPaid:"Paid", cicilanCurrent:"This Month", cicilanUpcoming:"Upcoming",
    cicilanMarkPaid:"Mark as Paid This Month", cicilanTotal2:"Total Monthly Instalments",
    cicilanRemain:"months left", cicilanOf:"of", noCicilan:"No instalments yet",
    cicilanDesc:"Instalments are auto-deducted from monthly income",
    cicilanSaved:"ok:Instalment saved", cicilanDeleted:"del:Instalment deleted",
    cicilanPaidToast:"ok:Marked as paid",
    cicilanAlreadyPaid:"Already paid this month",
    // Reminder
    reminderTitle:"Transaction Reminder", reminderDesc:"Notif if you haven't logged expenses today",
    reminderTime:"Reminder Time", reminderDays:"Active Days",
    reminderSmart:"Smart Reminder", reminderSmartDesc:"Skip if you already have transactions today",
    reminderPreview:"Notification Preview",
    reminderNotifTitle:"💸 Haven't logged expenses today!",
    reminderNotifBody:"Don't forget to record your transactions 🐱",
    reminderOn:"ok:Reminder activated!", reminderOff:"info:Reminder disabled",
    // Tags
    tags:"Tags", addTag:"Add Tag", editTag:"Edit Tag", noTags:"No tags yet",
    tagPlaceholder:"e.g. holiday, wedding...", tagSuggestions:"Tag Suggestions",
    tagFilter:"Filter by Tag", tagAll:"All", tagStats:"Summary by Tag",
    tagTx:"transactions", tagAdded:"ok:Tag added", tagDeleted:"del:Tag deleted",
    tagSaved:"ok:Tag saved",
    toastReminderOn:"ok:Daily reminder set for 9 PM", toastReminderOff:"info:Reminder disabled",
    shareSummary:"Share Summary", shareCopied:"ok:Summary copied!", shareWhatsapp:"Share to WhatsApp", shareCopy:"Copy Text",
    shareTitle:"Finance Report", swipeHint:"← Swipe to delete",
    addExpense:"+ Add Expense", addRecurring:"Add Recurring", recurringTx:"RECURRING",
    recurDay:"Day", recurEach:"every month", recurDeleted:"Recurring deleted", recurEdited:"Recurring updated", dayLabel:"Day (1-31):",
    autoApply:"Auto-apply", autoApplyDesc:"Recorded automatically each month on due date",
    allCategories:"All Categories", breakdownCat:"Category Breakdown", trend8w:"8-Week Trend",
    sortNewest:"Newest", sortOldest:"Oldest", sortHighest:"Highest", sortLowest:"Lowest",
    totalExpense:"TOTAL SPENDING", totalToday:"TODAY\'S TOTAL", perCategory:"By Category",
    txDetail:"Transactions", insightToday:"Today\'s Insight", topSpend:"Top:",
    aboveAvg:"Above daily average", belowAvg:"Below daily average",
    budgetMonthly:"MONTHLY BUDGET", notEnoughData:"Not enough data",
    notEnoughDataDesc:"The monthly comparison chart will appear once you have data from 2 different months.",
    goalRemaining:"Need", goalRemainingMore:"more", showMore:"Show More",
    insightMore:"more than", insightLess:"less than", insightFrom:"last month",
    insightUp:"up", insightDown:"down",
    previewHeader:"Preview Header",
    deleteTxTitle:"Delete Transaction?", deleteTxDesc:"This transaction will be permanently deleted.",
    backupOk:"Backup downloaded", restoreOk:"Backup restored!",
    restoreConfirm:"Restore this backup? Current data will be replaced.",
    backupInvalid:"Invalid backup file",
    showMore:"Lihat Lebih", backupData:"Backup Data", backupDesc:"Download all data as JSON", restoreBackup:"Pulihkan Backup", restoreDesc:"Import from backup file", resetDesc:"Delete all data permanently", dataSubtitle:"Backup, pulihkan & reset", restoreConfirmMsg:"Restore this backup? Current data will be replaced.",
  }
};
